<h1 style="font-size: 32px; text-align: center;">Introduction to Computer Programming for the Physical Sciences</h1>
<h2 style="font-size: 24px; text-align: center;">Joseph F. Hennawi</h2>
<h3 style="font-size: 24px; text-align: center;">Winter 2024</h2>

## Working on Section Problems

<ul style="list-style: none;">
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Get into groups of 2 or 3, with at least one laptop per group.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Discuss with each other and attempt each problem yourselves first without AI support for 10-15 mins.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>Input the problem prompt into the AI chatbox, use its answer to verify your own, or to learn how it should be solved.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>For section problems, you can omit most of the commenting and focus on learning coding. For more difficult problems, minimal comments are still recommended as a way of organizing your own thoughts.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Please abide by the <b><a href="https://github.com/enigma-igm/Phys29/blob/main/using_AI_tools.md">Policy and Guidelines on Using AI Tools</a></b></li>

# Section 1

## Problem 1

1. Write a function with a for loop inside it to return the factorial of x, f (x) = x!, where x is passed in as an argument.

2. Write a function using recursion to return the factorial of an argument, f (x) = x!, by implementing the recursion relation f (0) = 1, f (n) = nf (n − 1).

In [1]:
def factorial_forloop(x):
    result = 1
    for i in range(1, x+1):
        result *= i
    return result

def factorial_recursion(x):
    if x == 1:
        return 1
    else:
        return x * factorial(x-1)



0


## Problem 2

Compute the sum of the even numbers between 2 and 100 (inclusive) four ways:

• Use a for loop over the integers
    
• Create an array from 2 to 100 using numpy.arange() with a step size of 2, then
sum it using numpy.sum()

• Create an array from 1 to 50 using numpy.arange(), double it, and sum it

• Create an array from 0 to 100 and take every second element, then sum it

In [2]:
import numpy as np
even_numbers = np.arange(2, 101, 2)
print(even_numbers.sum())

one_to_fifty = np.arange(1, 51)
print(2 * (one_to_fifty.sum()))

result = 0
one_to_hunred = np.arange(1, 101)
for i in one_to_hunred:
    if i % 2 == 0:
        result += i
print(result)
        



2550
2550
2550


## Problem 3

Generate 5 random number from a Gaussian distribution of mean 6 and standard deviation 3. (Google numpy functions and find the right ones to use)

In [4]:
print(np.random.normal(6, 3, 5))

[2.67727806 2.79734112 8.22025704 6.68044563 6.31290906]


## Problem 4

This problem will give a very brief introduction to multidimensional arrays.

• Using np.array, create a 3 × 3 numpy array called x with first row 0, 1, and 2; second row 3, 4, and 5; and third row 6, 7, and 8.

• Do the same thing by first creating a one dimensional array of nine elements using np.arange, and then np.reshape; the new shape will be (3, 3).

• How do you index the central element 4 of your 3 × 3 array x?

• For multidimensional arrays, np.sum can also take an argument known as axis. Execute the following code on your 3 × 3 array x:
```
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
```
What does np.sum with no axis argument do? What are the axis=0 and axis=1 arguments doing?

In [11]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.arange(1, 10).reshape(3, 3)
print(array2[1, 1])
print(array1)

print(np.sum(array2)) # sum of all elements
print(np.sum(array2, axis=0)) # sum of each column
print(np.sum(array2, axis=1)) # sum of each row


5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
